name: Apply

on:
  workflow_dispatch:
    inputs:
      hosts:
        type: choice
        description: Hosts?
        options: 
        - all
        - localhost
        
      gather-facts:
        type: boolean
        description: Gather facts?
      

jobs:
  Apply:
    timeout-minutes: 360
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
